language: node_js

before_script:
  - npm install

node_js:
  - "8"

script:
  - npm run test

before_deploy:
  - npm run doc

deploy:
  provider:  pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: master

notifications:
  email:
    on_success: never
